### ISSUE TITLE
README.md => doing pip install pre-reqs and error

### ISSUE THREAD

**Issue by abitofalchemy** [IngoScholtes/pyTempNets#15]
`> pip install git+git://github.com/IngoScholtes/pyTempNets.git` on an Ubuntu like system is a process that depends on libraries to be installed on a system like: libxml2, libz, dfftpack, and lapack/blas to name a few.   As the dependencies are being sorted out, each time one has to run the pip install line --it takes a long time (depending on the system).  

Is there a way to gradually 'install' pyTempNets?

Should I clone the git repo and use python setup.py install ?

**Comment by romanc** [comment]
`pyTempNets` makes havy use of numpy and scipy packages of python. Numpy being dependent on blas and Scipy on lapack. This is normal behavior and yes, building blas/lapack from source might take a long time. Many Linux distributions do however offer numpy and scipy packages prebuilt to be installed from the distributions package manager. This might be faster than using pip assuming pip is building from source and your package manager not. On high performance computing nodes numpy/scipy might even be available as module to load.

Cloning the repo and using `setup.py install` should result in the same installation procedure as the proposed installation via pip and the git protocol.

**Comment by IngoScholtes** [comment]
Another hint: It may be a good idea to start from the Anaconda python distribution [1], as it comes shipped with many of the dependencies already installed. For me, on a fresh Ubuntu with Anaconda installed, installation of pyTempNets is fairly fast. 

[1] https://www.continuum.io/downloads
